### PR TITLE
Update babel version to 6

### PR DESCRIPTION
**Pull request by STRML**

### CODE REVIEW

**Comment by seanhess** [comment]
Hi @STRML, thanks for the PR. I have a couple concerns. 
1. Why do you depend on babel-cli? That's something you usually install at the system level, and each project has its own babel lib dependency. 
2. Why did you remove "default" from the export? That was intentional. 
3. I'm not familiar with the babel "presets". What do they do?

**Comment by STRML** [comment]
Hey @seanhess ,
1. In Babel 6, the `babel` package has been deprecated. You need to use `babel-cli` to use the `babel` command. The docs [encourage local installation](https://babeljs.io/docs/usage/cli/).
2. The semantics of CommonJS compatibility changed in Babel6. Previously, default exports (incorrectly) assigned to the root `module.exports`, so that line would work as you expected. Now, it (correctly) assigns to `.default`. If I didn't change that line, the export would look like:
   
   ``` javascript
   module.exports = {default: {readFile, Type, Property, validate}}
   ```
   
   In general there is no good reason to use `export default` with an object.
3. Here's [a reference on presets](https://babeljs.io/docs/usage/cli/). In short, Babel 6, by default, does nothing, unlike Babel 5 which contained a number of transforms by default. Presets are collections of plugins that emulate the groupings from Babel 5. They are required to do any transformation at all.

**Comment by seanhess** [comment]
Thanks. I've been out of the loop playing with Elm for a while, and I wanted to make sure this was well-informed.

**Comment by STRML** [comment]
:+1:

I have a bunch more that will build on this - things are constantly in flux so it's difficult to stay up to date.

**Pull request merged**
